#!/bin/sh

# programs used by this script
OPENSSL=`which openssl`
HEAD=`which head`
TR=`which tr`

# 8,16,32,64,128 char, lower case letters and numbers
$OPENSSL rand -base64 256 | $TR -dc 'a-z0-9' | $HEAD -c 8; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-z0-9' | $HEAD -c 16; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-z0-9' | $HEAD -c 32; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-z0-9' | $HEAD -c 64; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-z0-9' | $HEAD -c 128; echo ''

# 8,16,32,64,128 char, upper and lower case letters, numbers
$OPENSSL rand -base64 256 | $TR -dc 'a-zA-Z0-9' | $HEAD -c 8; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-zA-Z0-9' | $HEAD -c 16; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-zA-Z0-9' | $HEAD -c 32; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-zA-Z0-9' | $HEAD -c 64; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-zA-Z0-9' | $HEAD -c 128; echo ''

# 8,16,32,64,128 char, upper and lower case letters, numbers, limited special characters
$OPENSSL rand -base64 256 | $TR -dc 'a-zAZ0-9*()-+=' | $HEAD -c 8; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-zAZ0-9*()-+=' | $HEAD -c 16; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-zAZ0-9*()-+=' | $HEAD -c 32; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-zAZ0-9*()-+=' | $HEAD -c 64; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-zAZ0-9*()-+=' | $HEAD -c 128; echo ''

# 8,16,32,64,128 char, upper and lower case letters, numbers, most special characters
$OPENSSL rand -base64 256 | $TR -dc 'a-zAZ0-9{}()[]#:;^,.?!|&_`~@$%\/*+-=' | $HEAD -c 8; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-zAZ0-9{}()[]#:;^,.?!|&_`~@$%\/*+-=' | $HEAD -c 16; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-zAZ0-9{}()[]#:;^,.?!|&_`~@$%\/*+-=' | $HEAD -c 32; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-zAZ0-9{}()[]#:;^,.?!|&_`~@$%\/*+-=' | $HEAD -c 64; echo ''
$OPENSSL rand -base64 256 | $TR -dc 'a-zAZ0-9{}()[]#:;^,.?!|&_`~@$%\/*+-=' | $HEAD -c 128; echo ''
